name: CI/CD BookApi to AWS Lambda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest


    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup .NET SDK (match your project version)
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x

      # 3️⃣ Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # 4️⃣ Build the project
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # 5️⃣ Run tests
      - name: Test
        run: dotnet test --no-build --verbosity normal

      # 6️⃣ Publish for Lambda
      - name: Publish project
        run: dotnet publish BookApi.csproj -c Release -o ./publish

      # 7️⃣ Create zip package
      - name: Zip Lambda package
        run: |
          cd publish
          zip -r ../BookApi.zip .
          cd ..

      # 8️⃣ Deploy to AWS Lambda
      - name: Deploy to AWS Lambda
        uses: aws-actions/aws-cli@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
          command: |
            aws lambda update-function-code --function-name BookApiLambda --zip-file fileb://BookApi.zip
